export const COMPANY_COURT_OPTIONS: string[] = [
  'Balassagyarmati Törvényszék Cégbírósága',
  'Budapest Környéki Törvényszék Cégbírósága',
  'Debreceni Törvényszék Cégbírósága',
  'Egri Törvényszék Cégbírósága',
  'Fővárosi Törvényszék Cégbírósága',
  'Gyulai Törvényszék Cégbírósága',
  'Győri Törvényszék Cégbírósága',
  'Kaposvári Törvényszék Cégbírósága',
  'Kecskeméti Törvényszék Cégbírósága',
  'Miskolci Törvényszék Cégbírósága',
  'Nyíregyházi Törvényszék Cégbírósága',
  'Pécsi Törvényszék Cégbírósága',
  'Szegedi Törvényszék Cégbírósága',
  'Szekszárdi Törvényszék Cégbírósága',
  'Székesfehérvári Törvényszék Cégbírósága',
  'Szolnoki Törvényszék Cégbírósága',
  'Szombathelyi Törvényszék Cégbírósága',
  'Tatabányai Törvényszék Cégbírósága',
  'Veszprémi Törvényszék Cégbírósága',
  'Zalaegerszegi Törvényszék Cégbírósága',
];
